### ISSUE TITLE
Load in progress gizmo doesn't show up, can't find the cancel texture in the patch

### ISSUE THREAD

**Issue by marr75** [SmashPhil/LoadingInProgress#4]
This mod uses 
```csharp
__instance.LoadingInProgressOrReadyToLaunch && (element as Command_Action)?.icon == CancelLoadCommandTex
```
...to find the cancel loading command. Finding a gizmo based on its texture may be a bit fragile, as in my game, with the textures modified by DocWorld, AI Upscaled Textures, and Vanilla Expanded, it never finds the cancel gizmo.

Reading the Rimworld source code for CompTransporter, I settled on using this for the cancel element:
```csharp
"CommandCancelLoad".Translate() == commandElement.defaultLabel || commandElement.icon == CompTransporter.CancelLoadCommandTex;
```
...and it works.

Even simpler, though, the only gizmos being yielded by the method you're patching are "Cancel", "Last Group", "Select Group", and "Next Group". It's probably much simpler to just yield your load gizmo as soon as you've detected `__instance.LoadingInProgressOrReadyToLaunch`, this will put the gizmo one slot left of where you were adding it but it's so much simpler than finding the cancel button.

For example:
```csharp
public static IEnumerable<Gizmo> BoardTransporterInProgress(IEnumerable<Gizmo> __result, CompTransporter __instance)
{
    if (__instance.LoadingInProgressOrReadyToLaunch)
    {
        var transporterGroup = __instance.TransportersInGroup(__instance.parent.Map);
        var reloadCommand = new Command_ReloadTransporters
        {
            defaultLabel = transporterGroup.Count > 1
                ? "CommandReloadTransporter".Translate(transporterGroup.Count)
                : "CommandReloadTransporterSingle".Translate(),
            defaultDesc = "CommandReloadTransporterDesc".Translate(),
            icon = LoadCommandTex,
            transComp = __instance,
            transporters = transporterGroup
        };
        yield return reloadCommand;
    }
    foreach (var element in __result)
    {
        yield return element;
    }
}
```

As an added side effect, GetEnumerator is abstracted away and you won't get a warning about not disposing of the enumerator anymore. There are some outdated Unity superstitions about foreach loops that may be valid for older versions of Unity but generally, foreach will perform identically to more complicated for and while loops these days and prevents a lot of other bugs (the Kerbal Space Program code is LOUSY with bugs from bad iteration because of this superstition).

**Comment by SmashPhil** [comment]
Thanks for the tip, I just made a similar change.
